# Generated by Django 6.0.3 on 2026-05-20 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_creditcard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditcard',
            old_name='card_number_masked',
            new_name='card_number_raw',
        ),
    ]
