# Generated by Django 6.0.3 on 2026-05-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_card_number_masked_creditcard_card_number_raw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcard',
            name='card_number_raw',
        ),
        migrations.AddField(
            model_name='creditcard',
            name='card_last_four',
            field=models.CharField(default=0, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditcard',
            name='card_number_secure',
            field=models.CharField(default='0000', max_length=255),
            preserve_default=False,
        ),
    ]
