"""
Django settings for django_store project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# PLEASE, don't use this secret key in a production environment. 
# This is just for development purposes and project functionality testing. 
# In a production environment, you should generate a unique and secure secret key.
# You can see it like a flaw in the project, but it's necessary for practical testing the functionality of the project.
SECRET_KEY = 'django-insecure-m2mx8!+p^_+vth)618)z6-mxxsns42iax)7*qn4m5nfo0o#)7r'

# But if you want to use an environment variable for the secret key, you can uncomment the following lines and 
# set the SECRET_KEY in your environment variables.
# load_dotenv()
# SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!

# FLAW A05 (Security Misconfiguration):
# The DEBUG setting is set to True, which can expose sensitive information about the application
# in the event of an error. In a production environment, 
# this should be set to False to prevent information leakage.
DEBUG = True

# FIX FOR VULNERABILITY A05 (Security Misconfiguration):
# To mitigate the risk of information leakage,
# it is recommended to set DEBUG to False in a production environment.
# DEBUG = False

# FLAW A03 (Stored XSS):
# The SESSION_COOKIE_HTTPONLY setting is set to False, which allows client-side scripts 
# to access the session cookie. 
SESSION_COOKIE_HTTPONLY = False

# FIX FOR VULNERABILITY A03 (Stored XSS):
# To mitigate the risk of stored XSS attacks, 
# it is recommended to set SESSION_COOKIE_HTTPONLY to True.

# SESSION_COOKIE_HTTPONLY = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_tailwind_cli',
    'users',
    'products',
    'dashboard',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'django_store.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_store.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "assets"]

# Database models
AUTH_USER_MODEL = 'users.User'